name: OpenWrt GitHub Builder

on:
  workflow_dispatch:  # 手動ボタン（Run workflow）だけ

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/openwrt/buildbot/buildworker-v3.11.8:latest

    steps:
    - name: Checkout Your Repository
      uses: actions/checkout@v4

    - name: Run Builder Script
      run: |
        # ワークスペース全体の所有権をbuildbotユーザーに変更
        chown -R buildbot:buildbot $GITHUB_WORKSPACE
        chmod +x build.sh
        
        # 【修正】sudoの代わりに、コンテナに必ず入っている su コマンドで一般ユーザーを実行します
        su buildbot -c "./build.sh"

    - name: Upload Firmware to GitHub Releases
      uses: softprops/action-gh-release@v2
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: openwrt-wsr3200ax4s-${{ github.sha }}
        files: openwrt/bin/targets/mediatek/mt7622/*
