name: OpenWrt GitHub Builder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Your Repository
      uses: actions/checkout@v4

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ runs-on }}-openwrt-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runs-on }}-openwrt-ccache-      

    - name: Run Builder Script
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Upload Firmware to GitHub Releases
      uses: softprops/action-gh-release@v2
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: openwrt-wsr3200ax4s-${{ github.sha }}
        files: openwrt/bin/targets/mediatek/mt7622/*
